apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  app.kubernetes.io/environment: {{ .Values.environment | quote }}
  labels:
    app.kubernetes.io/name: assignment-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: assignment-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http