apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  labels:
    app.kubernetes.io/name: assignment-frontend
    app.kubernetes.io/environment: {{ .Values.environment | quote }}

data:
  config.js: |
    window.APP_CONFIG = {
      API_BASE_URL: {{ .Values.frontend.apiBaseUrl | quote }}
    };