sonar.projectName=assignment
sonar.sources=backend/app,frontend
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.pytest_cache/**
sonar.python.version=3.12